-- Migration: add public_api_key to company_accounts.
--
-- Separate from the existing `api_token` (a scraped session/cookie token used
-- against the private api.olaclick.app endpoints). `public_api_key` is an
-- OlaClick Public API key (olk_live_...) generated by the restaurant under
-- Integrations > API Keys, used against public-api.olaclick.app/v1. It powers
-- the combo-stats sync (per-order detail fetch) and is the long-term auth path.

ALTER TABLE company_accounts ADD COLUMN IF NOT EXISTS public_api_key TEXT;

COMMENT ON COLUMN company_accounts.public_api_key IS 'OlaClick Public API key (olk_live_...) for public-api.olaclick.app/v1; used by combo-stats sync.';
